#!/bin/sh
#
# post-receive

PROJECT_NAME=${0##*/};
#PATH=$(cd $(dirname $0); cd ../; pwd)
PATH="/usr/local/bin"
#wget -q "http://localhost:8080/job/${PROJECT_NAME}/build?delay=0"
wget -q "http://localhost:8080/job/TestProject/build?delay=0"

if [ "$?" -eq 0 ]; then
  echo "Jenkins build run."
else
  echo "Jenkins build failed."
fi


